Vanilla-OS/apx

cmd/upgrade.go

If applied, this patch fixes the spelling of the `upgradeUsage` function in cmd/upgrade.go.

chore(upgrade): fix spelling of upgradeUsage function

---

cmd/list.go
man/apx.1

If applied, this patch will add an `--installed` flag to the `list` command, similar to the `--upgradable` flag.

feat(list): add --installed flag to list command

---

cmd/autoremove.go
cmd/clean.go
cmd/enter.go
cmd/export.go
cmd/initialize.go
cmd/install.go
cmd/list.go
cmd/purge.go
cmd/remove.go
cmd/root.go
cmd/run.go
cmd/search.go
cmd/show.go
cmd/unexport.go
cmd/update.go
cmd/upgrade.go
main.go

If applied, this patch will add package level variables for container type and name, then set them in a PersistentPreRun function of the root command, applied to all children of the root command. Deletes much code.

feat(container): add package flags, DRY up functions

---

cmd/root.go
config/config.json
core/container.go
core/pkgmanager.go
main.go
settings/config.go

**Add --apt to use Ubuntu containers**
This way if config.json is configured to be something different than
apt, (so the default container _isn't_ Ubuntu), Ubuntu can still be used
as container
**Reduce the config file to the bare minimum and make it optional**
Now Ubuntu is an option in the code itself, there is no need to specify
it's commands in the config file any more. Thus we can reduce it to just
a container_name, the image to use and the package manager to use for
that image.
The config file is now also completely optional. If it isn't configured
(either by a distribution package or by the user itself) apx will try to
detect the config values from the host system. If it's an unsupported
setup (e.g. no known package manager) then it'll error out and instruct
the user to setup a …

Add --apt to use Ubuntu containers when default is set to something else and reduce the config file to the bare minimum and make it optional

---

cmd/autoremove.go
cmd/clean.go
cmd/enter.go
cmd/export.go
cmd/initialize.go
cmd/install.go
cmd/list.go
cmd/purge.go
cmd/remove.go
cmd/root.go
cmd/run.go
cmd/search.go
cmd/show.go
cmd/unexport.go
cmd/update.go
cmd/upgrade.go
core/connection.go
core/container.go
core/essentials.go
core/pkgmanager.go
main.go
man/apx.1
settings/config.go

If merged, this patch allows arbitrary extra managed containers specified with `--name` flag.

feat(containers): allow arbitrary container names

---

core/container.go
settings/config.go

apx currently uses non-standard commands like `which` and `lsb_release`, this PR replaces them for more portable alternatives.
**Replace 'which' usage for the more standard 'command -v'**
'which' is actually a Debianism, which just happens to be available in
most distros. 'command -v' is actually the standard way to check if a
tool exists in $PATH
**Use /etc/os-release rather than lsb_release to detect the OS**
lsb_release is not something that is installed on every distro, but
/etc/os-release is. So use that to detect the host system rather than
lsb_release

Make apx more portable

---

.gitignore
cmd/root.go
main.go

If applied, this patch will automatically set viper flag values to matching environment variables when they have the `APX_` prefix.
ex: 
`APX_AUR=true apx list` will run apx list in the arch container without specifying the --aur flag manually.
Perfect when used in combination with `direnv` to use a specific container for a specific project directory.
requires flag values be read using viper.GetXX().

feat: automatic environment variable matching to flags

---

config/config.json
core/container.go
core/essentials.go
settings/config.go

Since apx is just a wrapper around distrobox, it could be used on other distros as well. With this modification it works perfectly on Arch, by changing the `distroboxpath` in `config.json` to `/usr/bin/distrobox`.
I could probably also work on NixOS with the correct path, but I haven't tested it yet.

Move distrobox path to config.json

---

cmd/export.go
core/container.go

Adds `--bin=[binary_name]` option to `apx export`, to allow exporting a binary from a container to the host system.
A shell script created using `distrobox-export` will be placed at `~/.local/bin` with the same name as the binary, unless a command with the same name already exists in the host's $PATH. If that is the case, it will export with a prefix relative to the container (e.g. apt_[bin] for apx_managed, aur_[bin] for Arch, etc).

Export binary option

---

debian/control

Missed build-deps in the first PR.

chore: remove extraneous deps from build-depends

---

README.md

If merged this PR will add documentation to the README about working with vendored go modules.

chore: update readme with vendoring information

---

cmd/export.go

If the user runs `apx export` without providing an application name, the program would just crash. This pr checks whether an argument was provided and, if not, prints a useful error message to the user.

Export: don't crash when user didn't provide an application name:

---

core/connection.go
core/container.go

This pull request aims to improve the way that internet connection is checked by APX in order to be simpler, faster and lighter. The simple switch from `http.Get()` to `net.Dial()` actually improved the speed of the internet connection check in **~8-10x** while internet is `CONNECTED`, and **~1.5-1.15x** the speed when it's `DISCONNECTED`.
I also implemented two parameters to the function, `host` and `port` to provide an simple way to select more suitable test servers in different areas of the code and their needs. For example, the actual single implementation of `CheckConnection()` in the current state of APX is used to check internet connection before accessing `docker.io`. So, I also pointed the test server to their domain instead of `google.com`.
All tests below were made in my own …

Better connection check

---

core/container.go
vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
vendor/github.com/magiconair/properties/CHANGELOG.md
vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
vendor/modules.txt

Ensures `~/.local/bin` exists before exporting a binary. Fixes `apx export --bin` silently failing due to missing directory.

Export bin dir fix

---

cmd/show.go
core/pkgmanager.go

This PR adds a new flag to `apx show` to return only whether a certain package is installed or not. 
This will be necessary for our gnome-software plugin to verify which packages from the appstream file are already installed during the refine process.

Add isinstalled flag to apx show

---

cmd/remove.go
cmd/unexport.go
core/container.go

Same as `apx unexport [app]` but for binaries. Used through the `--bin` flag.

Unexport binary

---

cmd/show.go

Adds exit status to `apx show -i [package]` so the gnome-software plugin doesn't have to compare whole strings to check whether the application is installed.

Exit status on show -i

---

core/pkgmanager.go

As mentioned in [this issue](https://github.com/bitrise-io/bitrise/issues/433#issuecomment-256116057), using `dpkg -l`'s exit code for ensuring a package is installed is unreliable. Instead, we should be using `dpkg -s`.

Accurately check package is installed

---

cmd/run.go

If applied this patch sets the "interspersed" property of flags to false, effectively treating all text after the `run` command as arguments to the `run` command and not flags to the `apx` command.
fixes #88

fix(run): set interspersed flags to false for run command

---

cmd/root.go

If merged, this PR adds a storage configuration file for podman if it doesn't exist. The configuration sets `vfs` as the default storage, which fixes the errors about storage configuration being over-ridden.

fix(storage): add configuration for podman on first run

---

README.md
cmd/root.go
core/container.go
core/pkgmanager.go
lang/en/cmd_help
main.go
man/apx.1
settings/config.go

- Added **openSUSE** (`zypper`) flag to apx.
- Added **Void** (Linux) [`xbps`] flag to apx.
- Fixed `export --bin`.
- ~~`apx export --bin` doesn't work with Void. [But all other commands work as expected]~~, Fixed by @matbme.
- `autoremove` subcommand isn't present in `zypper`. [So it is marked as not implemented]
https://github.com/Vanilla-OS/vanilla-control-center/pull/96
Fig. Neofetch in Void (Linux) container [Renamed to `xbps`]
Fig. Neofetch in openSUSE container
- All commands has been tested (by running `go build` and executing the binary) and works as expected and issues encountered are listed above.

Add zypper, xbps (Void Linux) to apx, fix export bin

---

core/container.go
core/pkgmanager.go

When running `apx --aur init` when another Arch container had already been created in the past, the initialization script would download a newer version of `yay` and break installation, since there would be two directories in `~/.local/src/yay` matching the wildcard. 
This PR removes any existing versions of Yay from that directory before downloading it.
As a bonus, I also removed the `-v` flag from `tar` so it doesn't output random file names during initialization.

init: Remove previous versions of yay

---

cmd/autoremove.go
cmd/clean.go
cmd/update.go
cmd/upgrade.go
core/container.go

Adds the new flag `--all` for `autoremove`, `clean`, `update`, and `upgrade`, which will repeat the action for all existing containers.
Fixes #60 (and maybe #85)

`--all` for certain actions

---

cmd/install.go

This change adds back the --allow-unfree flag to the `apx install` command when the `nix` package manager is used.

Add allow-unfree flag back to apx --nix

---

settings/config.go

Application/distro default configuration is normally put in /usr/share and the user can copy the config file to /etc to override it. This way the distro can make sure to always provide a correct default configuration without having to deal with not overwriting the user's changes.

Read config from /usr/share/apx as well

---

main.go

- Bugfix: The Nix command heading displayed separately.
Before:-
After:-

Nix: Fix Command Summary

---

core/container.go

If merged, this PR will ignore errors that come from inside the shell. This prevents `apx` from displaying an error message when the command that is run returns non-zero return values.
fixes #116

fix: don't show apx failure when shell command returns error

---

cmd/upgrade.go
locales/en.yml

If approved, this PR will fix a bad index error when running `apx --nix upgrade` with no arguments.

fix: require package name for nix upgrade

---

cmd/install.go
cmd/remove.go

Export/unexport desktop application with binary name, which solves the issue where some .desktop files weren't removed when uninstalling a package.
Closes #32.

Use binary name to (un)export desktop app

---

cmd/install.go
core/utils.go

Automatically moving the deb file without user consent is bad. We should copy it to a usertemp instead.
Closes #91.

sideload: Copy deb instead of moving

---

cmd/initialize.go
cmd/install.go
core/nix.go
locales/en.yml

If merged, this change will add a flag to `apx install` to be used with the nix package manager to allow insecure packages to be installed.  Insecure in this case means packages with known vulnerabilities - davinci-resolve is the test case.
This also modifies the `--nix init` command to add a prompt asking if the user wants to allow insecure packages.
fixes #151

add allow-insecure flag to install

---

.gitmodules
Makefile
README.md
config/config.json

This adds `distrobox` as a submodule in this repo and creates a Makefile to make installing and building apx easier.

Add makefile and distrobox as submodule

---

Makefile

Runs `mkdir` as root when trying to create `/etc/apx`, fixes #166

Fix permission error when running make install

---

core/pkgmanager.go

- `update` command now only displays a message
- This is due to installing upgraded packages through a command that usually only syncs package listings in other containers possibly causing unexpected behaviour for the user
- `-Sy` was not used due to stability concerns, as updating package listings without installing the updated packages can cause AUR builds to fail
- This is not an error message, and is instead a simple `echo`. This is to avoid interfering with the `--all` flag
- `upgrade` command now also syncs package repos (`-Syu`) due to `update` no longer being implemented
- `clean` command now mirrors the behaviour of `apt clean`, no longer behaving like `apt autoremove`
- `autoremove` command is now implemented
- `list` command now lists all packages, rather than only packages …

Tweaks to command behaviour for the AUR container

---

main.go

This PR:
Current:
Additionally, if no error code is given but there was still an error, an exit code of 1 is now used

Produced exit codes are now actually used as exit codes

---

config/apx.json

After the building of the project, the `distrobox` binary is not anymore in `/usr/lib/apx/distrobox` but it is stored in `/usr/share/apx/distrobox`. This fix solves the following error when APX is created by building from source:
```
One or more core components are not available. 
Please refer to our documentation at https://documentation.vanillaos.org/
2023/06/25 22:32:04 distrobox is not installed
```

Fixed "not available core component" error

---

Makefile

Changed `/etc/apx/config.json` to `/etc/apx/apx.json` name because `config.json` was the old name of the configuration file that currently is `apx.json`. This PR will fix the error generated by running `apx` binary generated by the building of `apx-git` package:
```
Unable to read config file: 
Config File "apx" Not Found in "[/home/athena/athena-apx/config /home/athena/config /home/athena/.config/apx /etc/apx /usr/share/apx]"
```
Indeed, it cannot find `Config File "apx"` because it has still the old name `config.json`.

Fixed config file stale name

---

Makefile

`chmod 644 ${DESTDIR}${PREFIX}/share/man/*/man1/apx*` causes an error during the `sudo make install` because currently, a folder between `man` and `man1` does not exist, so the `chmod` in error and the building fails.
Since in the source files there is only `man/man1/apx.1`, it is suggested to delete the rows containing `${DESTDIR}${PREFIX}/share/man/*/man1/apx*`.

Deleted rows related to ${DESTDIR}${PREFIX}/share/man/*/man1/apx*

---

.github/workflows/go-pr.yml
.github/workflows/go.yml
.github/workflows/goreleaser.yml
sonar-project.properties

Updated version of https://github.com/Vanilla-OS/apx/pull/233 with default branch set to `v2`.

CI: Update workflows and set branch to v2

---

Makefile

Change the distrobox installation prefix to apx/distrobox so that apx finds distrobox in the expected location.

fix:[close #292] Change distrobox install path in Makefile

---

core/dbox.go

Displays the distrobox output when creating a new command, allowing the user to track the status of the command.

Feat: Display distrobox output in create command

---

Makefile

Adds the `build` target as a requirement for `install`, so that running `make install` without `build` wouldn't cause an error. Also Adds `uninstall-manpages` to the `uninstall` target

fu: add requirements to install and uninstall targets

---

core/dbox.go
core/subSystem.go

This PR fixes some issues when exporting/unexporting binaries and also improves command error descriptions.

fix: Export/unexport

---

locales/en.yml

fix: typo in subsystems string

---

.github/dependabot.yml
.github/workflows/go.yml
cmd/pkgManagers.go
cmd/runtime.go
cmd/stacks.go
cmd/subsyStems.go
core/dbox.go
core/essentials.go
core/pkgManager.go
core/stack.go
core/subSystem.go
lang/language.go
main.go
man/man1/apx.1
settings/config.go

- Update the man page.
- Update copyright year.
- Bump `actions/upload-artifact` version to v4.
- Add dependabot config for Go and GitHub action updates.

cleanup: update files

---

.github/workflows/sonar.yml

Reverts Vanilla-OS/apx#349
The push parameter isn't required in the Sonar workflow as automated Sonar check already runs on the main branch and it provides a report on commit like this https://github.com/Vanilla-OS/apx/runs/24139228654. So having both is redundant, so this PR reverts the change.

Revert "fu/ci: update Sonar workflow to run on push to main"

---

.github/workflows/go.yml

This PR adds the newly created Github Action that checks for missing translation strings in our Golang projects. I noticed we have quite a few of these issues in ABRoot, Apx, etc and this action should prevent us from making these mistakes in the future.
The workflow will fail (for now) since Apx has a ton of missing translation strings, but I'll fix them in a separate PR.

Add missing strings workflow

---

cmd/runtime.go
cmd/stacks.go
cmd/subsyStems.go
locales/en.yml

Fix missing or incorrect translation strings and improve readability for subsystem runtime command parsing by breaking down the function.
Pinging @kbdharun again since I had to add missing text.

fix: missing strings, refactor runtime commands

---

cmd/pkgManagers.go
cmd/runtime.go
cmd/stacks.go
cmd/subsyStems.go
locales/en.yml

fix: Add missing strings

---

config/apx.json
settings/config.go

This closes #362 
During the configuration process, APX will try to locate and utilize Distrobox from the PATH if it is not found in the default path.

Using Distrobox in PATH

---

go.mod
go.sum
locales/en.yml
main.go

Updates liborchid to v0.6.0 which allows us to add translation strings for usage.
@kbdharun this PR adds new strings

feat: Bump Orchird to v0.6.0, usage localization

---

core/pkgManager.go
core/stack.go
core/utils.go

Closes #371 
1. Added an utility function to check whether YAML or YML file based on their availability.
2. Updated references to hardcoded .yaml files with utility function.
~**NOTE TO REVIEWERS:** Regards to the utility function **ChooseYamlFile**, can you provide any suggestions on the name.~

feat/371 Add YML extension support for stacks and pkgmanagers

---

core/subSystem.go

- escape spaces when creating stack label
- escape spaces when creating name label
Closes #393

fix:[close #393] escape spaces when creating labels

---

Makefile

This is bad practice and users who want to install apx systemwide should invoke `sudo make` themselves.

fix(Makefile): don't use `sudo`

---

Makefile

* add `GO` variable to specify the path to the `go` binary
* make `BINARY_NAME` a target, so `make install` only rebuilds if the binary is not present
* assign variables using `:=` (simple expansion) to avoid potential gotchas caused by recursive expansion

feat(Makefile): GO variable, several improvements

---

core/subSystem.go
sonar-project.properties

Increasing the buffer size silences the error:
```
jardon@lagann:~/Projects/apx$ ./apx subsystems list
error reading binaries: bufio.Scanner: token too long
error reading binaries: bufio.Scanner: token too long
INFO  Found 1 subsystems:
┼┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
┊ NAME ┊ STACK       ┊ STATUS  ┊ PKGS ┊
┼┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
┊ test ┊ vanilla-dev ┊ Created ┊ 0    ┊
┼┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
```
closes #396

fix:[#396] increase buffer length for exported bin

---

cmd/pkgManagers.go
locales/en.yml

- check for built-in and error
- add english translation for error

fix: disallow updating built-in package managers

---

cmd/stacks.go

the first item in the list of packages for a stack is not on a new line and is not part of the list at all.  this change moves the package to the beginning of the list for clearer formatting
old:
```
INFO  Do you want to confirm the current packages list? git
- vim
- neofetch
```
new:
```
INFO  Do you want to confirm the current packages list?
- git
- vim
- neofetch
```

fix: move first package in stack packages to list

---

cmd/pkgManagers.go

- use string reader for pkgm update input handling
```
jardon@lagann:~/Projects/apx$ ./apx pkgmanagers show yum
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name       ┊ yum                   ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ NeedSudo   ┊ false                 ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ AutoRemove ┊ yum autoremove -v     ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Clean      ┊ yum clean             ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Install    ┊ yum                   ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ List       ┊ nstall                ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Purge      ┊ v                     ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Remove     ┊ yum remove            ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Search     ┊ yum …
```

fix:[#408] use string reader for pkgm update input

---

cmd/stacks.go
locales/en.yml

this PR addresses both of the below issues in one sweep.  it reworks the prompting of the user for an update.
- stacks update asks if pkgs need to be updated
- takes a space-separated list of packages to replace
```
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
INFO  Type a new base or confirm the current one (ubuntu:noble):
INFO  Choose a new package manager or confirm the current one (apt):
INFO  You have not provided any packages to install in the stack. Do you want to add some now?[y/N]
y
INFO  Type the packages you want to install in the stack, separated by a space:
neofetch vim
INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
INFO  Type a new base or confirm the current one (ubuntu:noble):
INFO  Choose a new package manager or confirm …
```

fix:[#411] stacks update asks for new list of pkgs

---

docs/articles/en/getting-started.md
docs/articles/en/introduction.md
docs/articles/en/understanding-pmss.md
docs/articles/en/working-w-pkgms.md
docs/articles/en/working-w-stacks.md
docs/articles/en/working-w-subsystems.md

feat(docs): add frontmatter to articles and format them

---

cmd/pkgManagers.go
locales/en.yml

close [#399]
- add default for autoremove
- add default for purge
I created constant variables for the name of each command, and also created a slice to define the order they should be presented, previously the order of the commands was random
A new translation string was also added

feat:[#399] set pkgm input defaults

---

cmd/stacks.go

- use formatted println with stack name substitution
```
./apx stacks new
INFO  Choose a name:
bionic
ERROR   A stack with the name '%s' already exists.
```
becomes:
```
./apx stacks new
INFO  Choose a name:
bionic
ERROR   A stack with the name 'bionic' already exists.
```

fix: use formatted println for stack exists error

---

cmd/stacks.go
core/subSystem.go
locales/en.yml

- add check for stack in use before removing subsystem
- add error message for in use stack in locales
```bash
./apx stacks rm -n noble
```
```
ERROR   The stack is used in 1 subsystems:
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
┊ NAME         ┊ STACK ┊ STATUS                   ┊ PKGS ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
┊ vso-waydroid ┊ noble ┊ Exited (130) 5 weeks ago ┊ 0    ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
```
relates #427

fix:[#427] refuse to remove stack if in use

---

main.go

Exit with generic (1) error if error exists
```bash
apx snapcraft run "/usr/bin/echo pass"
```
```
Error: crun: executable file `/usr/bin/echo pass` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
Error: An error occurred while executing the command: exit status 127
Usage:
apx snapcraft run [flags]
Flags:
-h, --help   help for run
ERROR   An error occurred while executing the command: exit status 127
```
```bash
echo $?
```
```
1
```
relates #434

fix:[#434] exit with 1 if error is detected

---

cmd/subsyStems.go
locales/en.yml

closes: #437 
While testing this in a virtual machine I noticed that apx-gui can create containers with command names so this needs to be fixed in apx-gui as well (they cannot be used as containers, they are just displayed in the panel and when trying to use them in apx-gui they display the output of the command)

feat: forbid use commands names as container name

---

core/dbox.go

remove the ioutil discard on stdout. 
```bash
APX_VERBOSE=1 ./apx test-apx enter
```
```
Runing a command:
Command: /usr/bin/podman ps -a --format {{.ID}}|{{.CreatedAt}}|{{.Status}}|{{.Labels}}|{{.Names}}
captureOutput: true
muteOutput: false
rootFull: false
detachedMode: false
Runing a command:
Command: /usr/share/apx/distrobox/distrobox enter apx-test-apx
captureOutput: false
muteOutput: false
rootFull: false
detachedMode: false
jardon@apx-test-apx:/var/home/jardon/Projects/apx$ exit
```
closes #449

fix:[#449] remove stdout discard

---

core/subSystem.go

increase the subsystem exported binary scanner buffer token size.
closes #450

fix:[#450] increase exported bin scan buffer token size

---

core/subSystem.go

check for both rootful and rootless containers instead of just rootful
```
Running a command:
Command: /usr/bin/podman ps -a --format {{.ID}}|{{.CreatedAt}}|{{.Status}}|{{.Labels}}|{{.Names}}
captureOutput: true
muteOutput: false
rootFull: false
detachedMode: false
Running a command:
Command: /usr/bin/podman ps -a --format {{.ID}}|{{.CreatedAt}}|{{.Status}}|{{.Labels}}|{{.Names}}
captureOutput: true
muteOutput: false
rootFull: false
detachedMode: false
Running a command:
Command: /usr/bin/pkexec /usr/bin/podman ps -a --format {{.ID}}|{{.CreatedAt}}|{{.Status}}|{{.Labels}}|{{.Names}}
captureOutput: true
muteOutput: false
rootFull: true
detachedMode: false
ERROR   The stack is used in 5 subsystems:
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┼
┊ NAME          ┊ STACK  ┊ …
```

fix:[#454] list all subsystems for stack

---

core/subSystem.go

i rewrote this to only scan the first 3 lines.  this fixes the issues, but its still possible to hit a bin that has a line that exceeds the limit.  its unlikely, but if we want to be extra sure this doesnt pop back up again, i can use `bufio.Reader` which doesnt have a token limit
closes #458

fix: [#458] restrict buffer to read beginning of file
